version:[1]version-number
os:[1]operating-system-name
files:
[2]-[1]source: /index.html
[4]destination: /var/www/html/ 
permissions:
[2]-[1]object:[1]object-specification
[4]pattern:[1]pattern-specification
[4]except:[1]exception-specification
[4]owner:[1]owner-account-name
[4]group:[1]group-name
[4]mode:[1]mode-specification
[4]acls: 
[6]-[1]acls-specification 
[4]context:
[6]user:[1]user-specification
[6]type:[1]type-specification
[6]range:[1]range-specification
[4]type:
[6]-[1]object-type
hooks:
[2]deployment-lifecycle-event-name:
[4]-[1]location: scripts/dep.sh
[6]timeout:[1]timeout-in-seconds
[6]runas:[1]user-name